using UnityEngine;
using System.Collections.Generic;
using System.IO;

public class ProceduralBeatMapGenerator : MonoBehaviour
{
    [Header("Audio")]
    public AudioClip audioClip;
    public float bpm = 103f;

    [Header("Settings")]
    public string songName = "AutoGenerated";
    public int difficulty = 1;

    [Header("Pattern Density")]
    [Tooltip("몇 박자마다 노트 생성")]
    public int beatsPerNote = 2;

    [Header("Timing")]
    public float introDelay = 3f;  // ★ 추가! 인트로 시간 ★

    [Header("Randomization")]
    public bool avoidConsecutiveSame = true;

    [Header("Obstacles")]
    [Range(0f, 0.3f)]
    public float obstacleProbability = 0.1f;

    [Header("Preview")]
    public int estimatedNoteCount = 0;
    public float estimatedDuration = 0f;

    void OnValidate()
    {
        if (audioClip != null)
        {
            estimatedDuration = audioClip.length;
            float beatInterval = 60f / bpm;
            int totalBeats = Mathf.FloorToInt(estimatedDuration / beatInterval);
            estimatedNoteCount = totalBeats / beatsPerNote;
        }
    }

    [ContextMenu("Generate Full Song BeatMap")]
    public void GenerateFullSong()
    {
        if (audioClip == null)
        {
            Debug.LogError("Audio Clip not assigned!");
            return;
        }

        Debug.Log("=== Starting BeatMap Generation ===");

        BeatMapData beatMap = new BeatMapData
        {
            bpm = bpm,
            songName = songName,
            difficulty = difficulty,
            notes = new List<NoteData>()
        };

        float songLength = audioClip.length;
        float beatInterval = 60f / bpm;
        int totalBeats = Mathf.FloorToInt(songLength / beatInterval);

        Debug.Log($"Song: {audioClip.name}");
        Debug.Log($"Length: {songLength:F1}s");
        Debug.Log($"BPM: {bpm} → Beat interval: {beatInterval:F2}s");
        Debug.Log($"Intro Delay: {introDelay}s");  // ★ 추가
        Debug.Log($"Total beats: {totalBeats}");
        Debug.Log($"Generating note every {beatsPerNote} beats...");

        int lastDrum = -1;
        int hitCount = 0;
        int obstacleCount = 0;

        // ★ introDelay부터 시작! ★
        int startBeat = Mathf.CeilToInt(introDelay / beatInterval);

        for (int beat = startBeat; beat < totalBeats; beat += beatsPerNote)
        {
            float time = beat * beatInterval;

            if (time > songLength - 1f)
                break;

            bool isObstacle = Random.value < obstacleProbability;

            int drum;
            if (avoidConsecutiveSame && lastDrum != -1)
            {
                do
                {
                    drum = Random.Range(0, 4);
                }
                while (drum == lastDrum);
            }
            else
            {
                drum = Random.Range(0, 4);
            }

            beatMap.notes.Add(new NoteData
            {
                time = time,
                drum = drum,
                type = isObstacle ? "obstacle" : "hit"
            });

            lastDrum = drum;

            if (isObstacle)
                obstacleCount++;
            else
                hitCount++;
        }

        SaveBeatMap(beatMap);

        Debug.Log("=== Generation Complete! ===");
        Debug.Log($"★ Total notes: {beatMap.notes.Count}");
        Debug.Log($"  - Hit notes: {hitCount}");
        Debug.Log($"  - Obstacles: {obstacleCount}");
        Debug.Log($"★ First note at: {beatMap.notes[0].time:F2}s");  // ★ 추가
        Debug.Log($"★ Notes per second: {beatMap.notes.Count / songLength:F1}");
    }

    void SaveBeatMap(BeatMapData data)
    {
        string json = JsonUtility.ToJson(data, true);

        string folderPath = Path.Combine(Application.dataPath, "Resources/BeatMaps/Generated");
        Directory.CreateDirectory(folderPath);

        string fileName = $"{songName}_Difficulty{difficulty}_Auto.json";
        string filePath = Path.Combine(folderPath, fileName);

        File.WriteAllText(filePath, json);

        Debug.Log($"★ Saved to: {filePath}");

#if UNITY_EDITOR
        UnityEditor.AssetDatabase.Refresh();
#endif
    }
}
